version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'jgs2-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
      - "21:21"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VSFTPD_CONF-./config/vsftpd/vsftpd.conf}:/etc/vsftpd.conf
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    entrypoint:
      - ${DOCUMENT_ROOT-./bin/webserver/entrypoint.sh}
  mysql:
    build: ./bin/mysql
    container_name: 'jgs2-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ${DOCUMENT_ROOT-./bin/mysql/entrypoint.sql}:/docker-entrypoint-initdb.d/create_users_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'jgs2-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions