version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'jgs2-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'jgs2-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ${DOCUMENT_ROOT-./bin/mysql/entrypoint.sql}:/docker-entrypoint-initdb.d/create_users_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'jgs2-phpmyadmin'
    restart: 'always'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  ftp:
    build:
      context: ./bin/vsftpd/
    container_name: 'jgs2-ftp'
    restart: 'always'
    links:
      - webserver
    ports:
      - "212:21"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/storage/ftp
      - ${DOCUMENT_ROOT-./bin/vsftpd/vsftpd.chroot_list}:/etc/vsftpd.chroot_list
      - ${DOCUMENT_ROOT-./bin/vsftpd/shells}:/etc/shells
      - ${DOCUMENT_ROOT-./bin/vsftpd/conf/etc/vsftpd/vsftpd.conf}:/etc/vsftpd.conf
    environment:
      - FTP_USER=dev
      - FTP_PASSWORD=dev
      - FTP_PATH=/storage/ftp
  redis:
    container_name: 'jgs2-redis'
    image: redis:latest
    volumes:
      - ${REDIS_DATA_DIR-./data/redis}:/data
    ports:
      - "6379:6379"